/*
 * Dungeons and Trolls
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.10.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DungeonsandtrollsLevel struct {
	Level int32 `json:"level,omitempty"`
	Width int32 `json:"width,omitempty"`
	Height int32 `json:"height,omitempty"`
	Horror float32 `json:"horror,omitempty"`
	DeprecationInSeconds int32 `json:"deprecationInSeconds,omitempty"`
	Objects []DungeonsandtrollsMapObjects `json:"objects,omitempty"`
	FogOfWar []DungeonsandtrollsFogOfWarMap `json:"fogOfWar,omitempty"`
	PlayerMap []DungeonsandtrollsPlayerSpecificMap `json:"playerMap,omitempty"`
}
