/*
 * Dungeons and Trolls
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.5.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DungeonsandtrollsSkillGenericFlags struct {
	RequiresOutOfCombat bool `json:"requiresOutOfCombat,omitempty"`
	RequiresLineOfSight bool `json:"requiresLineOfSight,omitempty"`
	Passive bool `json:"passive,omitempty"`
}
