/*
 * Dungeons and Trolls
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DungeonsandtrollsSkillAttributes struct {
	Strength *DungeonsandtrollsAttributes `json:"strength,omitempty"`
	Dexterity *DungeonsandtrollsAttributes `json:"dexterity,omitempty"`
	Intelligence *DungeonsandtrollsAttributes `json:"intelligence,omitempty"`
	Willpower *DungeonsandtrollsAttributes `json:"willpower,omitempty"`
	Constitution *DungeonsandtrollsAttributes `json:"constitution,omitempty"`
	SlashResist *DungeonsandtrollsAttributes `json:"slashResist,omitempty"`
	PierceResist *DungeonsandtrollsAttributes `json:"pierceResist,omitempty"`
	FireResist *DungeonsandtrollsAttributes `json:"fireResist,omitempty"`
	PoisonResist *DungeonsandtrollsAttributes `json:"poisonResist,omitempty"`
	ElectricResist *DungeonsandtrollsAttributes `json:"electricResist,omitempty"`
	Life *DungeonsandtrollsAttributes `json:"life,omitempty"`
	Stamina *DungeonsandtrollsAttributes `json:"stamina,omitempty"`
	Mana *DungeonsandtrollsAttributes `json:"mana,omitempty"`
	Constant *DungeonsandtrollsAttributes `json:"constant,omitempty"`
}
