/*
 * Dungeons and Trolls
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DungeonsandtrollsAttributes struct {
	Strength float32 `json:"strength,omitempty"`
	Dexterity float32 `json:"dexterity,omitempty"`
	Intelligence float32 `json:"intelligence,omitempty"`
	Willpower float32 `json:"willpower,omitempty"`
	Constitution float32 `json:"constitution,omitempty"`
	SlashResist float32 `json:"slashResist,omitempty"`
	PierceResist float32 `json:"pierceResist,omitempty"`
	FireResist float32 `json:"fireResist,omitempty"`
	PoisonResist float32 `json:"poisonResist,omitempty"`
	ElectricResist float32 `json:"electricResist,omitempty"`
	Life float32 `json:"life,omitempty"`
	Stamina float32 `json:"stamina,omitempty"`
	Mana float32 `json:"mana,omitempty"`
	Constant float32 `json:"constant,omitempty"`
}
