/*
 * Dungeons and Trolls
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.6.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DungeonsandtrollsSkillSpecificFlags struct {
	Movement bool `json:"movement,omitempty"`
	Knockback bool `json:"knockback,omitempty"`
	Stun bool `json:"stun,omitempty"`
	GroundEffect bool `json:"groundEffect,omitempty"`
}
