/*
 * Dungeons and Trolls
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DungeonsandtrollsSkillFlags struct {
	RequiresAlone bool `json:"requiresAlone,omitempty"`
	RequiresLineOfSight bool `json:"requiresLineOfSight,omitempty"`
	AllowTargetSelf bool `json:"allowTargetSelf,omitempty"`
	Movement bool `json:"movement,omitempty"`
	Knockback bool `json:"knockback,omitempty"`
	Stun bool `json:"stun,omitempty"`
	GroundEffect bool `json:"groundEffect,omitempty"`
	Passive bool `json:"passive,omitempty"`
}
