/*
 * Dungeons and Trolls
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.3.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SkillTarget string

// List of SkillTarget
const (
	NONE_SkillTarget SkillTarget = "none"
	POSITION_SkillTarget SkillTarget = "position"
	CHARACTER_SkillTarget SkillTarget = "character"
)
